FROM nginx:1.27-alpine

COPY index.html /usr/share/nginx/html/index.html
COPY intake.html /usr/share/nginx/html/intake.html
COPY welcome.html /usr/share/nginx/html/welcome.html
COPY nginx.unified.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
